### ISSUE TITLE
Select and SelectMany

### ISSUE THREAD

**Issue by justinmchase** [hazzik/Maybe#1]
I wrote a blog post with some ideas you might like: http://justinmchase.com/2012/09/13/maybe-with-linq-2/

Basically if in addition to With you make methods called Select and SelectMany then you can use linq syntax to build maybe expressions. It's kind of nice. Just a suggestion. I was thinking about making a Maybe package on nuget but since you already did I will just make a few suggestions here instead. Good job. 

Also the presence of two "Withs" (or Bind as I called them) seems unnecessary. I think you can get it to work with just one.

**Comment by bleis-tift** [comment]
@justinmchase 
Unfortunately this library does not provide any monads...
Don't you try [my library](https://github.com/LangExt/LangExt), if you want to use a library that provides Option monad?

**Comment by hazzik** [comment]
@bleis-tift unfortunately I do not care if it is a "real monads" or "fake monads"

**Comment by hazzik** [comment]
Implemented in 6a312b88
